name: "Find Pull Requests with Update Keyword"
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  find-update-prs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Find PRs with Update Keyword
      id: find-prs
      uses: peter-evans/find-pull-request@v1
      with:
        search: 'update'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Print PR Links
      run: |
        for pr in ${{ steps.find-prs.outputs.number }}; do
          echo "https://github.com/${{ github.repository }}/pull/$pr"
        done

