name: remind review
on: [push]
jobs:
  send_pull_requests:
    runs-on: ubuntu-latest
    name: list pr - test
    steps:
      - name: listPullRequests
        uses: buildsville/list-pull-requests@v1
        id: list
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: '["WFR","update image"]'
          skip_hour: '24'
      - name: output information
        run: echo '${{ steps.list.outputs.pulls }}'
